# Generated by Django 5.0.11 on 2026-02-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
