# Generated by Django 5.0.11 on 2026-02-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_alter_fooditem_old_price'),
        ('orders', '0004_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartFood',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderFood',
        ),
    ]
