# Generated by Django 5.0.11 on 2026-02-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_cartitem_cartfood_rename_orderitem_orderfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartfood',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='orders.cart'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fooditems', to='orders.order'),
        ),
    ]
