# Generated by Django 5.0.11 on 2026-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_rename_price_fooditem_old_price_fooditem_discout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='old_price',
            field=models.FloatField(default=100),
        ),
    ]
