# Generated by Django 5.0.11 on 2026-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_alter_fooditem_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
